package:
  name: pywwt
  version: {{version}}

{{source}}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  build:
    - python
    - setuptools
    - nodejs

  run:
    - python
    - numpy >=1.9
    - matplotlib >=1.5
    - astropy >=1.0
    - requests
    - beautifulsoup4
    - python-dateutil
    - lxml
    - ipywidgets >=7.0
    - ipyevents
    - traitlets
    - pyqt
    - qtpy
    - flask
    - flask-cors
    - six
    - widgetsnbextension
    - jupyterlab
    - notebook
    - reproject

test:
  imports:
    - pywwt

about:
  home: http://github.com/WorldWideTelescope/pywwt
  license: BSD 3-Clause
  summary: Use WorldWideTelescope in Python
