package:
  name: pywwt
  version: {{version}}

{{source}}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  build:
    - python
    - setuptools

  run:
    - python
    - traitlets
    - ipywidgets >=7.0
    - astropy
    - qtpy
    - pyqt
    - widgetsnbextension
    - ipyevents

test:
  imports:
    - pywwt

about:
  home: http://github.com/WorldWideTelescope/pywwt
  license: BSD 3-Clause
  summary: Use WorldWideTelescope in Python
